#!/bin/bash
git="/usr/bin/git"
cmds="pull checkout"
echo "--------"
echo  "$(cd "$(dirname "${BASH_SOURCE[0]}")" > /dev/null 2>&1 && pwd)/git-check"
echo "$git" "$@"
echo "--------"
for cmd in $cmds
do
    if [ "$cmd" = "$1" ]
    then
        echo "$0"
        echo -n "Are you really sure you want to \"git $cmd\"? [y/N] "
        read chk
        if [ "$chk" != "y" ]
        then
            if [ "$chk" != "Y" ]
            then
                echo "Aborted"
                exit
            fi
        fi
    fi
done
exec "$git" "$@"
