#!/bin/bash
echo "$(dirname $0)/git-check is forwarding command to /usr/bin/git"
tmp="$(dirname "$0")/$?.tmp"
if [ "$1" = "pull" ]
then
    echo -n "This is a production account. Are you sure you want to git pull? [y/N] "
    read chk
    if [ "$chk" != "y" ]
    then
        if [ "$chk" != "Y" ]
        then
            echo "Aborting git pull command"
            exit
        fi
    fi
fi

exec /usr/bin/git "$@"


